# Generated by Django 4.2.7 on 2024-10-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='role_tenant',
        ),
    ]
