# Generated by Django 4.2.7 on 2024-10-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_userclass_class_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
    ]
