# Generated by Django 4.2.7 on 2024-10-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_alter_class_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='classes', to='engine.class'),
        ),
    ]
