# Generated by Django 4.2.7 on 2024-10-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_alter_userclass_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='address',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='settings',
        ),
        migrations.AddField(
            model_name='subject',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
