# Generated by Django 4.2.7 on 2024-10-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_rename_address_subject_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_code',
            new_name='code',
        ),
    ]
