# Generated by Django 4.2.7 on 2024-10-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
