# Generated by Django 4.2.7 on 2024-10-16 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_class',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userclass',
            name='class_instance',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to='engine.class'),
        ),
        migrations.AddField(
            model_name='userclass',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
