# Generated by Django 4.2.7 on 2024-10-16 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_alter_userclass_class_instance_alter_userclass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
