# Generated by Django 4.2.7 on 2024-10-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_alter_userclass_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='engine_user_email_2e7cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='engine_user_usernam_57d6f7_idx'),
        ),
    ]
