# Generated by Django 4.2.7 on 2024-10-16 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_user_engine_user_email_2e7cdf_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='userclass',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to='engine.class'),
        ),
        migrations.AlterField(
            model_name='userclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
