# Generated by Django 4.2.7 on 2024-10-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_classsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='number_of_periods',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='classsubject',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='engine.classsubject'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
