# Generated by Django 4.2.7 on 2024-10-20 13:41

import core.apps.engine.models_container.enum_type
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_remove_schedule_class_id_remove_schedule_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubjectscore',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='usersubjectscore',
            name='role_tenant',
        ),
        migrations.RemoveField(
            model_name='usersubjectscore',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='usersubjectscore',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usersubjectscore',
            name='Score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubjectscore',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subject_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubjectscore',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subject_score', to='engine.subject'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], default=core.apps.engine.models_container.enum_type.StatusClassSubjectEnum['ACTIVE'], max_length=50, null=True),
        ),
    ]
