# Generated by Django 4.2.7 on 2024-10-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_remove_usersubjectscore_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubjectscore',
            old_name='Score',
            new_name='score',
        ),
    ]
