# Generated by Django 4.2.7 on 2024-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_alter_notification_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
