# Generated by Django 4.2.7 on 2024-11-07 08:18

import core.apps.engine.models_container.enum_type
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubjectscore',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubjectscore',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CONFIRM', 'CONFIRM')], default=core.apps.engine.models_container.enum_type.StatusUserSubjectScoreEnum['OPEN'], max_length=50, null=True),
        ),
    ]
